/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Setup(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/gurksetup.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={materials.material_0}
      />
    </group>
  )
}

useGLTF.preload('/gurksetup.glb')
